// Mocks generated by Mockito 5.4.6 from annotations
// in traqtrace_app/test/features/epcis/screens/validation_rule_management_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter/material.dart' as _i13;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:traqtrace_app/core/cubit/system_settings_cubit.dart' as _i6;
import 'package:traqtrace_app/core/models/system_settings_model.dart' as _i7;
import 'package:traqtrace_app/core/theme/theme_cubit.dart' as _i5;
import 'package:traqtrace_app/data/services/auth_service/auth_service.dart'
    as _i3;
import 'package:traqtrace_app/features/auth/cubit/auth_cubit.dart' as _i11;
import 'package:traqtrace_app/features/auth/cubit/auth_state.dart' as _i4;
import 'package:traqtrace_app/data/models/auth/auth_models.dart' as _i12;
import 'package:traqtrace_app/features/epcis/models/validation_rule.dart'
    as _i8;
import 'package:traqtrace_app/features/epcis/providers/validation_rule_provider.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValidationRuleState_0 extends _i1.SmartFake
    implements _i2.ValidationRuleState {
  _FakeValidationRuleState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_2 extends _i1.SmartFake implements _i4.AuthState {
  _FakeAuthState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThemeState_3 extends _i1.SmartFake implements _i5.ThemeState {
  _FakeThemeState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSystemSettingsState_4 extends _i1.SmartFake
    implements _i6.SystemSettingsState {
  _FakeSystemSettingsState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDataClearStatistics_5 extends _i1.SmartFake
    implements _i7.DataClearStatistics {
  _FakeDataClearStatistics_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ValidationRuleCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidationRuleCubit extends _i1.Mock
    implements _i2.ValidationRuleCubit {
  MockValidationRuleCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.ValidationRule> get validationRules =>
      (super.noSuchMethod(
            Invocation.getter(#validationRules),
            returnValue: <_i8.ValidationRule>[],
          )
          as List<_i8.ValidationRule>);

  @override
  List<_i8.ValidationRule> get rules =>
      (super.noSuchMethod(
            Invocation.getter(#rules),
            returnValue: <_i8.ValidationRule>[],
          )
          as List<_i8.ValidationRule>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get loading =>
      (super.noSuchMethod(Invocation.getter(#loading), returnValue: false)
          as bool);

  @override
  List<_i8.ValidationRule> get enabledRules =>
      (super.noSuchMethod(
            Invocation.getter(#enabledRules),
            returnValue: <_i8.ValidationRule>[],
          )
          as List<_i8.ValidationRule>);

  @override
  _i2.ValidationRuleState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeValidationRuleState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.ValidationRuleState);

  @override
  _i9.Stream<_i2.ValidationRuleState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i2.ValidationRuleState>.empty(),
          )
          as _i9.Stream<_i2.ValidationRuleState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  List<_i8.ValidationRule> getRulesByEventType(_i8.EventType? eventType) =>
      (super.noSuchMethod(
            Invocation.method(#getRulesByEventType, [eventType]),
            returnValue: <_i8.ValidationRule>[],
          )
          as List<_i8.ValidationRule>);

  @override
  List<_i8.ValidationRule> getRulesByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getRulesByCategory, [category]),
            returnValue: <_i8.ValidationRule>[],
          )
          as List<_i8.ValidationRule>);

  @override
  _i8.ValidationRule? getRuleById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getRuleById, [id]))
          as _i8.ValidationRule?);

  @override
  _i8.ValidationRule? getRuleByRuleId(String? ruleId) =>
      (super.noSuchMethod(Invocation.method(#getRuleByRuleId, [ruleId]))
          as _i8.ValidationRule?);

  @override
  _i9.Future<void> loadSampleRules() =>
      (super.noSuchMethod(
            Invocation.method(#loadSampleRules, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> loadValidationRules() =>
      (super.noSuchMethod(
            Invocation.method(#loadValidationRules, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> toggleValidationRule(int? ruleId, bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleValidationRule, [ruleId, enabled]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i8.ValidationRule?> createValidationRule(
    _i8.ValidationRule? rule,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createValidationRule, [rule]),
            returnValue: _i9.Future<_i8.ValidationRule?>.value(),
          )
          as _i9.Future<_i8.ValidationRule?>);

  @override
  _i9.Future<_i8.ValidationRule?> updateValidationRule(
    int? ruleId,
    _i8.ValidationRule? rule,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateValidationRule, [ruleId, rule]),
            returnValue: _i9.Future<_i8.ValidationRule?>.value(),
          )
          as _i9.Future<_i8.ValidationRule?>);

  @override
  _i9.Future<bool> deleteValidationRule(int? ruleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteValidationRule, [ruleId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> searchValidationRules(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#searchValidationRules, [searchTerm]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> resetToDefaults() =>
      (super.noSuchMethod(
            Invocation.method(#resetToDefaults, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initializePredefinedRules() =>
      (super.noSuchMethod(
            Invocation.method(#initializePredefinedRules, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> reloadRules() =>
      (super.noSuchMethod(
            Invocation.method(#reloadRules, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i8.ValidationRule?> addRule(_i8.ValidationRule? rule) =>
      (super.noSuchMethod(
            Invocation.method(#addRule, [rule]),
            returnValue: _i9.Future<_i8.ValidationRule?>.value(),
          )
          as _i9.Future<_i8.ValidationRule?>);

  @override
  _i9.Future<_i8.ValidationRule?> updateRule(_i8.ValidationRule? rule) =>
      (super.noSuchMethod(
            Invocation.method(#updateRule, [rule]),
            returnValue: _i9.Future<_i8.ValidationRule?>.value(),
          )
          as _i9.Future<_i8.ValidationRule?>);

  @override
  _i9.Future<bool> deleteRule(_i8.ValidationRule? rule) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRule, [rule]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  List<_i8.ValidationRule> getPredefinedRules() =>
      (super.noSuchMethod(
            Invocation.method(#getPredefinedRules, []),
            returnValue: <_i8.ValidationRule>[],
          )
          as List<_i8.ValidationRule>);

  @override
  List<_i8.ValidationRule> getSampleAdvancedRules() =>
      (super.noSuchMethod(
            Invocation.method(#getSampleAdvancedRules, []),
            returnValue: <_i8.ValidationRule>[],
          )
          as List<_i8.ValidationRule>);

  @override
  void emit(_i2.ValidationRuleState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i2.ValidationRuleState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [AuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCubit extends _i1.Mock implements _i11.AuthCubit {
  MockAuthCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i3.AuthService);

  @override
  _i4.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_2(this, Invocation.getter(#state)),
          )
          as _i4.AuthState);

  @override
  _i9.Stream<_i4.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i4.AuthState>.empty(),
          )
          as _i9.Stream<_i4.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.Future<void> checkAuth() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuth, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> login(_i12.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> register(_i12.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> requestPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [email]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> validatePasswordResetToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validatePasswordResetToken, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> completePasswordReset(
    String? token,
    String? newPassword,
    String? confirmPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completePasswordReset, [
              token,
              newPassword,
              confirmPassword,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> verifyEmail(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void emit(_i4.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i4.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [ThemeCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeCubit extends _i1.Mock implements _i5.ThemeCubit {
  MockThemeCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);

  @override
  _i13.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i13.ThemeMode.system,
          )
          as _i13.ThemeMode);

  @override
  _i5.ThemeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeThemeState_3(this, Invocation.getter(#state)),
          )
          as _i5.ThemeState);

  @override
  _i9.Stream<_i5.ThemeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i5.ThemeState>.empty(),
          )
          as _i9.Stream<_i5.ThemeState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.Future<void> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setDarkMode(bool? isDark) =>
      (super.noSuchMethod(
            Invocation.method(#setDarkMode, [isDark]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> refreshFromProfile() =>
      (super.noSuchMethod(
            Invocation.method(#refreshFromProfile, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  bool getCurrentThemePreference() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentThemePreference, []),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void emit(_i5.ThemeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i5.ThemeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SystemSettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemSettingsCubit extends _i1.Mock
    implements _i6.SystemSettingsCubit {
  MockSystemSettingsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.SystemSettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSystemSettingsState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.SystemSettingsState);

  @override
  _i9.Stream<_i6.SystemSettingsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i6.SystemSettingsState>.empty(),
          )
          as _i9.Stream<_i6.SystemSettingsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.DataClearStatistics> loadDataStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#loadDataStatistics, []),
            returnValue: _i9.Future<_i7.DataClearStatistics>.value(
              _FakeDataClearStatistics_5(
                this,
                Invocation.method(#loadDataStatistics, []),
              ),
            ),
          )
          as _i9.Future<_i7.DataClearStatistics>);

  @override
  _i9.Future<void> changeIndustryMode({
    required _i7.IndustryMode? newMode,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeIndustryMode, [], {
              #newMode: newMode,
              #reason: reason,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.DataClearStatistics> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i9.Future<_i7.DataClearStatistics>.value(
              _FakeDataClearStatistics_5(
                this,
                Invocation.method(#clearAllData, []),
              ),
            ),
          )
          as _i9.Future<_i7.DataClearStatistics>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.SystemSettingsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i6.SystemSettingsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
