const Map<String, String> ssccTobaccoCountryOptions = {
  'USA': 'United States',
  'CAN': 'Canada',
  'MEX': 'Mexico',
  'GBR': 'United Kingdom',
  'DEU': 'Germany',
  'FRA': 'France',
  'ITA': 'Italy',
  'ESP': 'Spain',
  'NLD': 'Netherlands',
  'BEL': 'Belgium',
  'CHE': 'Switzerland',
  'AUT': 'Austria',
  'POL': 'Poland',
  'CZE': 'Czech Republic',
  'HUN': 'Hungary',
  'ROU': 'Romania',
  'BGR': 'Bulgaria',
  'GRC': 'Greece',
  'PRT': 'Portugal',
  'SWE': 'Sweden',
  'DNK': 'Denmark',
  'FIN': 'Finland',
  'NOR': 'Norway',
  'IRL': 'Ireland',
  'AUS': 'Australia',
  'NZL': 'New Zealand',
  'JPN': 'Japan',
  'KOR': 'South Korea',
  'CHN': 'China',
  'IND': 'India',
  'BRA': 'Brazil',
  'ARG': 'Argentina',
  'ZAF': 'South Africa',
  'ARE': 'United Arab Emirates',
  'SAU': 'Saudi Arabia',
  'TUR': 'Turkey',
  'RUS': 'Russia',
  'UKR': 'Ukraine',
  'SGP': 'Singapore',
  'MYS': 'Malaysia',
  'THA': 'Thailand',
  'IDN': 'Indonesia',
  'PHL': 'Philippines',
  'VNM': 'Vietnam',
};

const Map<String, String> ssccTobaccoUsStateOptions = {
  'AL': 'Alabama',
  'AK': 'Alaska',
  'AZ': 'Arizona',
  'AR': 'Arkansas',
  'CA': 'California',
  'CO': 'Colorado',
  'CT': 'Connecticut',
  'DE': 'Delaware',
  'FL': 'Florida',
  'GA': 'Georgia',
  'HI': 'Hawaii',
  'ID': 'Idaho',
  'IL': 'Illinois',
  'IN': 'Indiana',
  'IA': 'Iowa',
  'KS': 'Kansas',
  'KY': 'Kentucky',
  'LA': 'Louisiana',
  'ME': 'Maine',
  'MD': 'Maryland',
  'MA': 'Massachusetts',
  'MI': 'Michigan',
  'MN': 'Minnesota',
  'MS': 'Mississippi',
  'MO': 'Missouri',
  'MT': 'Montana',
  'NE': 'Nebraska',
  'NV': 'Nevada',
  'NH': 'New Hampshire',
  'NJ': 'New Jersey',
  'NM': 'New Mexico',
  'NY': 'New York',
  'NC': 'North Carolina',
  'ND': 'North Dakota',
  'OH': 'Ohio',
  'OK': 'Oklahoma',
  'OR': 'Oregon',
  'PA': 'Pennsylvania',
  'RI': 'Rhode Island',
  'SC': 'South Carolina',
  'SD': 'South Dakota',
  'TN': 'Tennessee',
  'TX': 'Texas',
  'UT': 'Utah',
  'VT': 'Vermont',
  'VA': 'Virginia',
  'WA': 'Washington',
  'WV': 'West Virginia',
  'WI': 'Wisconsin',
  'WY': 'Wyoming',
  'DC': 'District of Columbia',
  'PR': 'Puerto Rico',
};

const List<String> ssccTobaccoSealTypeOptions = [
  'Bolt Seal',
  'Cable Seal',
  'Padlock Seal',
  'Plastic Seal',
  'Metal Seal',
  'Electronic Seal',
  'RFID Seal',
  'Customs Seal',
  'Carrier Seal',
  'Shipper Seal',
];
