// Mocks generated by Mockito 5.4.6 from annotations
// in traqtrace_app/test/features/epcis/providers/validation_rule_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:traqtrace_app/data/services/validation_rule_service.dart' as _i3;
import 'package:traqtrace_app/features/epcis/models/validation_rule.dart'
    as _i2;


// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValidationRule_0 extends _i1.SmartFake
    implements _i2.ValidationRule {
  _FakeValidationRule_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ValidationRuleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidationRuleService extends _i1.Mock
    implements _i3.ValidationRuleService {
  MockValidationRuleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ValidationRule>> getAllRules() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRules, []),
            returnValue: _i4.Future<List<_i2.ValidationRule>>.value(
              <_i2.ValidationRule>[],
            ),
          )
          as _i4.Future<List<_i2.ValidationRule>>);

  @override
  _i4.Future<_i2.ValidationRule?> getRuleById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRuleById, [id]),
            returnValue: _i4.Future<_i2.ValidationRule?>.value(),
          )
          as _i4.Future<_i2.ValidationRule?>);

  @override
  _i4.Future<List<_i2.ValidationRule>> getEnabledRules() =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledRules, []),
            returnValue: _i4.Future<List<_i2.ValidationRule>>.value(
              <_i2.ValidationRule>[],
            ),
          )
          as _i4.Future<List<_i2.ValidationRule>>);

  @override
  _i4.Future<List<_i2.ValidationRule>> getRulesByEventType(String? eventType) =>
      (super.noSuchMethod(
            Invocation.method(#getRulesByEventType, [eventType]),
            returnValue: _i4.Future<List<_i2.ValidationRule>>.value(
              <_i2.ValidationRule>[],
            ),
          )
          as _i4.Future<List<_i2.ValidationRule>>);

  @override
  _i4.Future<_i2.ValidationRule> createRule(_i2.ValidationRule? rule) =>
      (super.noSuchMethod(
            Invocation.method(#createRule, [rule]),
            returnValue: _i4.Future<_i2.ValidationRule>.value(
              _FakeValidationRule_0(
                this,
                Invocation.method(#createRule, [rule]),
              ),
            ),
          )
          as _i4.Future<_i2.ValidationRule>);

  @override
  _i4.Future<_i2.ValidationRule?> updateRule(
    int? id,
    _i2.ValidationRule? rule,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRule, [id, rule]),
            returnValue: _i4.Future<_i2.ValidationRule?>.value(),
          )
          as _i4.Future<_i2.ValidationRule?>);

  @override
  _i4.Future<_i2.ValidationRule?> toggleRuleStatus(int? id, bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleRuleStatus, [id, enabled]),
            returnValue: _i4.Future<_i2.ValidationRule?>.value(),
          )
          as _i4.Future<_i2.ValidationRule?>);

  @override
  _i4.Future<bool> deleteRule(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRule, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.ValidationRule>> searchRules(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#searchRules, [searchTerm]),
            returnValue: _i4.Future<List<_i2.ValidationRule>>.value(
              <_i2.ValidationRule>[],
            ),
          )
          as _i4.Future<List<_i2.ValidationRule>>);

  @override
  _i4.Future<void> resetToDefaults() =>
      (super.noSuchMethod(
            Invocation.method(#resetToDefaults, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initializePredefinedRules() =>
      (super.noSuchMethod(
            Invocation.method(#initializePredefinedRules, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
